ci:
  skip:
    - poetry-lock
    - unittest
    - generate-docs
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 2.2.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
        name: check-yaml for mkdocs.yml
        files: ^mkdocs\.yml$
        args: [--unsafe]
    -   id: check-yaml
        name: check-yaml for other YAML files
        exclude: ^mkdocs\.yml$
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          [
            betterproto==2.0.0b7,
            httpx==0.28.1,
            types-aiofiles==24.1.0.20250822,
            types-passlib==1.7.7.20250602,
            pydantic==2.11.9,
          ]
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python -m unittest discover
        language: system
        types: [ python ]
        args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
        pass_filenames: false
    -   id: generate-docs
        name: generate-docs
        entry: python docs/generate_miners.py
        language: system
        types: [ python ]
        pass_filenames: false
